import tkinter as tk


BACKGROUND_PRIMARY = '#FFFFFF'
BACKGROUND_SECONDARY = '#ececec'
BACKGROUND_ACCENT = '#738aff'

FONT_ON_PRIMARY = '#131313'
FONT_ON_SECONDARY = '#131313'
FONT_ON_ACCENT = '#FFFFFF'
FONT_HINT = '#808080'

BUTTON_WARNING = '#d20707'
BUTTON_INFORMAL = '#d6d6d6'
BUTTON_ACCENT = '#738aff'

TOGGLE_FG_CHECKED = '#FFFFFF'
TOGGLE_BG_CHECKED = '#1bc127'
TOGGLE_FG_UNCHECKED = '#131313'
TOGGLE_BG_UNCHECKED = '#d6d6d6'

RELIEF = tk.RAISED
RELIEF_ENTRY = tk.FLAT
